// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvqccjsqgwwwcifejuux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2cWNjanNxZ3d3d2NpZmVqdXV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNzMwMjUsImV4cCI6MjA3MzY0OTAyNX0._OKaN4QD4nVrap-xLM-COXS6LF2bo7SmtHd3m7a0FYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});